defaults: &defaults
  # HTTP access mode:
  # 1. closed - Authenticate with HTTP basic
  # 2. open - Don't authenticate with HTTP basic
  http_basic_access_mode: closed
  http_basic_name: preview
  http_basic_password: dev  # Update this in production
  test_user_password: password

  application_name: YourInsiderZambia
  applications_folder: "/var/Apps"
  gemset_name: yourinsiderzambia-rails.5.x
  ruby_version: ruby-2.3.0
  deploy_user: deploy

  miniumum_version_of_bundler: ">=1.11.2"
  miniumum_version_of_rake: ">=11.1.1"

  # Multi-stage recipe settings
  # Virtual deployment
  virtual_deployment_path: virtual
  virtual_repository_deployment_branch: master
  virtual_server_name: rails.vm
  virtual_stage_name: virtual

  # Staging deployment
  staging_deployment_path: staging
  staging_repository_deployment_branch: master
  staging_server_name: asher.vps
  staging_stage_name: staging

  # Production deployment
  production_deployment_path: production
  production_repository_deployment_branch: master
  production_server_name: gad.vps
  production_stage_name: production

  # Asset vault
  asset_vault_path: /var/AssetsVault




development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

  # HTTP access mode:
  # 1. closed - Authenticate with HTTP basic
  # 2. open - Don't authenticate with HTTP basic
  http_basic_access_mode: closed
